#!/bin/sh
#
# Copyright (C) 2026 ImmortalWrt
#
# WiFi SSID / encryption / country defaults for Gemtek XR1710G / W1700K.
# These are written into board.json and consumed by mac80211.uc during
# wireless config generation, so they take effect on first boot without
# fighting uci-defaults timing issues.

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
gemtek,xr1710g-ubi|\
gemtek,w1700k-ubi)
	ucidef_set_country 'US'
	ucidef_set_wireless 2g 'ImmortalWrt-2G' 'psk2' '12345678'
	ucidef_set_wireless 5g 'ImmortalWrt-5G' 'sae-mixed' '12345678'
	ucidef_set_wireless 6g 'ImmortalWrt-6G' 'sae' '12345678'
	;;
esac

board_config_flush

exit 0
