#!/bin/sh
#
# Copyright (C) 2026 ImmortalWrt
#
# MT7996 tri-band WiFi 7 radio-level defaults for Gemtek XR1710G / W1700K.
# SSID / encryption / country are handled by board.d/03_wifi_defaults via
# board.json (consumed by mac80211.uc). This script only sets radio hardware
# parameters that have no board.json API.

. /lib/functions.sh

board=$(board_name)

case "$board" in
gemtek,xr1710g-ubi|\
gemtek,w1700k-ubi)
	for i in $(seq 1 20); do
		[ -d /sys/class/ieee80211/phy0 ] && break
		sleep 1
	done

	if ! uci -q get wireless.radio0 >/dev/null 2>&1; then
		/sbin/wifi config 2>/dev/null
	fi
	uci -q get wireless.radio0 >/dev/null 2>&1 || exit 0

	uci set wireless.radio0.channel='auto'
	uci set wireless.radio0.htmode='HE20'
	uci set wireless.radio0.txpower='28'
	uci set wireless.radio0.disabled='0'
	uci set wireless.radio0.he_mu_beamformer='0'
	uci set wireless.radio0.he_su_beamformer='1'

	uci set wireless.radio1.channel='36'
	uci set wireless.radio1.htmode='EHT160'
	uci set wireless.radio1.txpower='30'
	uci set wireless.radio1.disabled='0'
	uci set wireless.radio1.he_su_beamformer='1'
	uci set wireless.radio1.he_mu_beamformer='1'
	uci set wireless.radio1.eht_su_beamformer='1'
	uci set wireless.radio1.eht_mu_beamformer='1'
	uci set wireless.radio1.he_bss_color='2'
	uci set wireless.radio1.radar_background='1'

	uci set wireless.radio2.channel='37'
	uci set wireless.radio2.htmode='EHT320'
	uci set wireless.radio2.txpower='30'
	uci set wireless.radio2.disabled='0'
	uci set wireless.radio2.eht_su_beamformer='1'
	uci set wireless.radio2.eht_mu_beamformer='1'
	uci set wireless.radio2.he_su_beamformer='1'
	uci set wireless.radio2.he_mu_beamformer='1'
	uci set wireless.radio2.he_bss_color='1'
	uci set wireless.radio2.he_twt_responder='1'

	uci commit wireless
	;;
esac

exit 0
